framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_SENDER)%''thony.meyers@gmail.com'
        headers:
                From: '%env(MAILER_FROM)%''administrator <thony.meyers@gmail.com>'